server:
  port: 9040

app:
  name: no-axure
  version: 1.0.0

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:3306/noaxure
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/**/*_SqlMapper.xml,mapper/**/**/*_SqlMapper.xml
  plugins:
    sqlAudit: true
    logback: true
    systemLog: true
    cipherField: false
    eaiInterface: false

logging:
  level:
    com.example.noaxure: debug

